# Generated by Django 4.2.15 on 2024-09-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("salt", models.CharField(max_length=32)),
                ("last_activity_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("secret", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("nonce", models.CharField(max_length=64)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_wallet.wallet")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
