# Generated by Django 4.2.15 on 2024-09-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_role_name_role_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Guest"), (2, "Client"), (3, "Accountant"), (4, "Supervisor"), (5, "Admin")],
                null=True,
                unique=True,
            ),
        ),
    ]
